joomla:
  build: web
  links:
    - joomladb:mysql
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./data:/var/www/html/data

joomladb:
  build: db
  environment:
    MYSQL_ROOT_PASSWORD: example
